### ISSUE TITLE
Featured notes

### ISSUE THREAD

**Issue by rknightuk** [rothsandro/eleventy-notes#2]
Similar to favourites but set by the author. I already have this working on my version but I wanted to see if this was something you would want to add to the project before opening a PR. Example in `app.json`

```json
"featured": [
  "mastodon",
  "icons",
  "analytics",
  "lametric-alternative",
  "alfred"
],
"notes": [
// ...
]
```

Then I've added a featuredNotes collection and render them in `sidebar`.

If you want this in the project let me and I'll add a PR.

**Comment by rothsandro** [comment]
Do you need this as a separate section (Favorites / Featured / Notes / Tags)? As part of the notes section you could already create a "Featured" group (based on filename, folder or tag).

```json
{
  "sidebar": {
    "notes": [
      {
        "pattern": "^/(Getting Started)|(Next Steps)$",
        "label": "Featured"
      }
    ]
  }
}
```

**Comment by rknightuk** [comment]
Oh yeah of course I could 🤦‍♂️
