### ISSUE TITLE
Move the content into the content folder

### ISSUE THREAD

**Issue by imagepit** [rothsandro/eleventy-notes#31]
We want to move the content into the content folder as shown in the figure below. In this case, how should I change the setting?

<img width="799" alt="image" src="https://github.com/rothsandro/eleventy-notes/assets/3522645/a7276fc4-6cc7-460a-b66b-82e2c368bd39">

**Comment by rothsandro** [comment]
This is not supported, the `app.json` and `index.md` always have to be in the root. Other files could be moved into a content folder but the folder would be part of the URL (which is likely not what you want).

Is there a specific reason you want to move them into a separate folder?

**Comment by imagepit** [comment]
Thanks. I wanted to manage it as a docker image with only separate files to be written in markdown. I've been using a different static site generator and had separate folders like this.
I'll consider moving everything except index.md and app.json to the content folder.

**Comment by imagepit** [comment]
Understood. Thank you. This matter is closed.
