### ISSUE TITLE
Style <kbd> elements

### ISSUE THREAD

**Issue by uncenter** [rothsandro/eleventy-notes#35]
We could just use the existing "keypress" styling from the search bar, the hover animation looks cool.

<img width="251" alt="image" src="https://github.com/rothsandro/eleventy-notes/assets/47499684/d765ac64-c8c6-42a8-a15d-107166d8f87d">

**Comment by rothsandro** [comment]
Sorry for my late response, I took a break from coding.

Do you write HTML in your Markdown files to insert the kbd element or where do you want to use it?

**Comment by uncenter** [comment]
Well typically I use the syntax `[[Ctrl]] + [[C]]` but there interferes with the wikilink syntax...

**Comment by rothsandro** [comment]
Yes, that syntax would not work. Neither Markdown nor platforms like GitHub/Obsidian/... have a syntax for it. They just support using HTML directly (afaik). I would not like to introduce a special syntax that doesn't work in any other tool.

**Comment by uncenter** [comment]
Could just add styling for it and let users figure out how they want to add them?

**Comment by uncenter** [comment]
Thank you!
