### ISSUE TITLE
Slow builds in server mode?

### ISSUE THREAD

**Issue by pjeby** [rothsandro/eleventy-notes#44]
Just trying this out and it seems that changing even the body text of  just one note causes every page in the site to be regenerated, taking several seconds despite the small project size.  Disabling the "Eleventy-Plugin-Page-Assets-transform-parser" plugin cut the time almost in half, but it's still multiple seconds per change.  Is this normal/expected?

Given the build time appears linear in the number of notes, it seems like this could become quite challenging to use after adding a few hundred notes.

**Comment by pjeby** [comment]
After a bit more experimenting, I found that I can run `eleventy --serve --incremental` and the site refreshes in under a second; if I simultaneously run `eleventy --watch` in another terminal, the slower full site rebuild is still done but doesn't block the fast refresh for the changed page.

This seems like a (somewhat) reasonable workaround for local development, though it doesn't refresh any other pages automatically.  (It may be that this will get better when 11ty's incremental builds get better, though.)

**Comment by rothsandro** [comment]
Thanks for bringing this up and the analysis. Builds will definitely be slower than for a "plain" eleventy project because of asset handling, wikilinks and search. But I guess there is still room for improvement. I will need some time to further analyse the problem.

**Comment by rothsandro** [comment]
I just released [version 0.19.0](https://eleventy-notes.sandroroth.com/n/releases/changelog/) which includes a new search that is faster and asynchronous in dev mode, which makes rebuilds after a change faster. It was never that slow on my machine but now ~50% faster. Please give it a try when you have time and let me know if it helps.

I will keep the issue open as there is likely room for further improvements in other areas.

**Comment by pjeby** [comment]
It's definitely faster, but still 2-3 seconds instead of 5-6.  Not really *that* big a deal except that's for just the 40 notes in the start kit.  Putting a couple hundred notes in would still make it challenging.  At least the `serve --incremental` w/parallel `--watch` trick still works to keep it under 1s.

Very cool project, though!  I've since moved on from this as a choice for my immediate project docs need, but I still want to come back to it some time for notes publishing from Obsidian.  It seems almost tailor-made for that.

**Comment by rothsandro** [comment]
Thanks for testing it again and your feedback 👍. I will try to improve other areas (asset handling, ...) as well to further improve performance.

**Comment by rothsandro** [comment]
I just released v0.20.0 which further improves performance. Rebuilding the site in dev mode is ~80% faster compared to previous version on my machine.

**Comment by pjeby** [comment]
Very nice!  It's now doing about 120 pages/second on my machine without incremental building.
