### ISSUE TITLE
Suggestion: add support for markdown-it-containers

### ISSUE THREAD

**Issue by web0174** [rothsandro/eleventy-notes#46]
Hi, it would be nice if you could add support for [markdown-it-containers.](https://github.com/markdown-it/markdown-it-container) (or something similar....)
Almost all documentation generators have them and they are useful for attracting attention. 
They also give a more professional look to the site. 
I did a little [test](https://github.com/web0174/eleventy-notes-test) and it seems to work, 
but if you decide to add them, you will know what is the best way to do it. 
( 🙏 sorry for my English, I hope I managed to make myself understood). 
Ciao 👋🏻.

![Schermata 2024-01-26 alle 15 24 12](https://github.com/rothsandro/eleventy-notes/assets/8037897/405b9d33-bb99-4566-9375-da428dfc5e38)

**Comment by rothsandro** [comment]
I agree that this would be useful.


## Syntax 

There are two different syntaxes. The `:::` syntax is used by VitePress and Docusaurus. Both of them render a title inside the container but the plugin you mentioned doesn't.

```
::: info
Hello
:::
```

The alternative syntax is using blockquotes + `![type]`, which is used by GitHub and Obsidian.

```
> [!note]
> Hello
```

This is how it looks like on GitHub:

> [!NOTE]
> This is an example (read this on github.com)

I don't have a strong opinion on the syntax itself but I think the blockquote syntax would be a better match in this case. I try to be compatible with Obsidian stuff when possible and many users will likely host their content on GitHub.

Do you have a strong opinion or need for the `:::` syntax or custom containers without a title? If not, I will see if I can implement the blockquote syntax.

**Comment by web0174** [comment]
Hi, I don't have any preferences about the syntax.
Aesthetically I really like the GitHub style, in fact in the second test I did I was inspired by that.

![test-2](https://github.com/rothsandro/eleventy-notes/assets/8037897/a89446df-3d7e-434b-a6e5-b7958d27b81b)

However, I believe that the best choice is the one you consider most used and compatible. Thank you 👋🏻

**Comment by rothsandro** [comment]
**Feature shipped** 🎉 Eleventy Notes v0.22.0 now supports callouts. Read more about it in [the docs](https://eleventy-notes.sandroroth.com/n/writing/callouts/).

**Comment by web0174** [comment]
Hello, great job thank you very much. 👍
