### ISSUE TITLE
Question: methodology behind project structure

### ISSUE THREAD

**Issue by semanticdata** [rothsandro/eleventy-notes#49]
Hello,

New fan of the project; thank you for sharing it. 🙏

Out of curiosity, is there a reason for structuring the project from within `.app` instead of the more common `src` folder? Have you or someone else written about it? It looks interesting, and I would like to read more about it.

Thanks! 👋

**Comment by rothsandro** [comment]
The reason for this project structure is to better separate the app (template) from the content. This allows you to easily update to newer versions of the template by just replacing the `.app` folder. In more common project structure you often don't have a strict separation. The content either lives in a subfolder and you have to replace everything except the subfolder, or the content lives in the root with additional files like `package.json` and Eleventy config. Both is not ideal IMHO.

Another advantage: If you open the project in Markdown editor like Obsidian or iA Writer, the `.app` folder will automatically be hidden, so you can focus on your content. In more common project structure you would either see additional files or the content needs to live in a subfolder (which I don't like).

**Comment by semanticdata** [comment]
Thank you, I appreciate you for taking the time to explain. I look forward to contributing to the project in the future. 😄
