### ISSUE TITLE
Minor issue with incorrect path to default config file in Configuration File note

### ISSUE THREAD

**Issue by ktushar14** [rothsandro/eleventy-notes#55]
The relative path to `app-config.js` in [this line](https://github.com/rothsandro/eleventy-notes/blob/7bf8510e4ba132b6400cc414b38c5fefb3eaa07e/Features/Configuration%20file.md?plain=1#L13), `.app/app-config`, does not seem to work for me when testing a custom configuration file, but `"./.app/app-config"` does. (The project's own custom configuration file also contains the latter path: see [this line](https://github.com/rothsandro/eleventy-notes/blob/7bf8510e4ba132b6400cc414b38c5fefb3eaa07e/app.js#L2).)

My environment:
Ubuntu 22.04.4 LTS 64-bit
Google Chrome Version 127.0.6533.99 (Official Build) (64-bit)
npm version 10.7.0
eleventy-notes version 0.24.0

**Comment by rothsandro** [comment]
Thanks for reporting. You're right, `./.app/app-config` is the correct way, I fixed the docs.
