### ISSUE TITLE
Add configuration option for search placeholder text

### ISSUE THREAD

**Issue by uncenter** [rothsandro/eleventy-notes#59]
![CleanShot 2024-11-17 at 15 16 24](https://github.com/user-attachments/assets/2905bc7b-4a3c-4bb4-9436-e0cb15b5eee6)

I'd like to able to configure/override this "Search by title, content and #tags" text easily in the configuration file.

**Comment by rothsandro** [comment]
What text would you use? Just to understand your use case.

I think we don't allow any text configuration at the moment (except for user generated content, like groups in the nav). Adding this to the configuration doesn't feel right. I would rather add support for translations in the whole app (but that's a bit more work).

**Comment by uncenter** [comment]
This is for https://learn-eleventy.pages.dev/, I'd like to make it say "Search for lessons by title or content." which is how I have it on the deployed site. [Updating](https://github.com/uncenter/learn-eleventy/pull/4) at the minute and trying to avoid customizing .app as much this time.

**Comment by rothsandro** [comment]
Thanks for explanation, makes sense. I will see if adding translations is viable option.

**Comment by rothsandro** [comment]
I created a first prototype that adds translation to the search ui. With `@ts-check` enabled you'll get auto-complete for translation keys and the default translation value.

```ts
// @ts-check
import { defineTranslations } from "./.app/app-translations.js";

export const translations = defineTranslations({
  lang: "de",
  translations: {
    "search.input.placeholder": "Suchen...",
    "search.popover.placeholder": "Suche nach Titel, Inhalt und #tag",
    // ...
  },
});
```

**Comment by rothsandro** [comment]
Eleventy Notes v0.26.0 is released 🎉 It now supports translations for all UI elements. Read more about in the docs: https://eleventy-notes.sandroroth.com/n/features/language/
