### ISSUE TITLE
Resolve Sass deprecation warnings

### ISSUE THREAD

**Issue by uncenter** [rothsandro/eleventy-notes#60]
These won't happen with the current version of Sass eleventy-notes is on, but if you bump a few minor versions `@import` is deprecated as of v1.80.0: https://sass-lang.com/blog/import-is-deprecated/. You'll get these warnings until you resolve it.

```
DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
3 │ @import "./3-global/kbd";
  │         ^^^^^^^^^^^^^^^^
  ╵
    css/app.scss 3:9          @import
    css/app.tomato.scss 91:9  root stylesheet
```

**Comment by rothsandro** [comment]
Thanks for reporting. I will update and migrate the code.

**Comment by rothsandro** [comment]
Eleventy Notes v0.26.0 is released 🎉 It uses the latest sass version and styles are migrated.
