### ISSUE TITLE
Switch to Lucide Icons instead of Feather Icons

### ISSUE THREAD

**Issue by uncenter** [rothsandro/eleventy-notes#61]
[Lucide](https://lucide.dev/icons/) is a community maintained fork of Feather Icons, and has many more icons available (1539 compared to Feather's 287).

**Comment by rothsandro** [comment]
I started with Feather icons but later also added Tabler Icons for callouts. I would like to replace Feather in the future and only have a single icon library.

Do you have a specific needs for Lucide? Do you want to use the icons for additional links in the main navigation (the only place that supports customizable icons) or do you want to use icons somewhere else that is not officially supported by the template?

**Comment by uncenter** [comment]
For additional links yep. I bet Lucide would offer similar icons to whatever you are using Tabler for :)

**Comment by rothsandro** [comment]
Are there any good reasons for Lucide over Tabler (or reasons against Tabler)? Tabler has even more icons and als brand icons which Lucide hasn't (it has some but they are deprecated and no new ones will be added, e.g. Bluesky is missing).

**Comment by uncenter** [comment]
I prefer the look of Lucide over Tabler, as they are Feather-inspired. For logos I would use something like https://simpleicons.org if that is important.
